name: Java CI with Maven

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    
    - name: Create Maven Settings
      run: |
        mkdir -p ~/.m2
        echo "<settings>
          <profiles>
            <profile>
              <id>default</id>
              <activation>
                <activeByDefault>true</activeByDefault>
              </activation>
              <properties>
                <maven.compiler.source>11</maven.compiler.source>
                <maven.compiler.target>11</maven.compiler.target>
                <maven.compiler.release>11</maven.compiler.release>
              </properties>
            </profile>
          </profiles>
        </settings>" > ~/.m2/settings.xml
        
    - name: Clone FlowDroid 2.14.1
      run: |
        git clone https://github.com/secure-software-engineering/FlowDroid.git
        cd FlowDroid
        git checkout tags/v2.14.1
        
    - name: Build with Maven
      run: |
        cd FlowDroid
        mvn clean install -DskipTests -Dmaven.compiler.source=11 -Dmaven.compiler.target=11 -X

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: flowdroid-jar
        path: FlowDroid/soot-infoflow-cmd/target/soot-infoflow-cmd-jar-with-dependencies.jar
