name: Build FlowDroid 2.14.1

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Clone Soot Repository
      run: |
        git clone https://github.com/soot-oss/soot.git
        cd soot
        git checkout develop
    
    - name: Install Soot to Local Maven Repository
      run: |
        cd soot
        mvn clean install -DskipTests \
          -Dmaven.compiler.source=17 \
          -Dmaven.compiler.target=17
    
    - name: Clone FlowDroid Repository
      run: |
        git clone https://github.com/secure-software-engineering/FlowDroid.git
        cd FlowDroid
        git checkout v2.14.1
    
    - name: Create Maven Settings
      run: |
        mkdir -p ~/.m2
        cat > ~/.m2/settings.xml << EOF
        <settings>
          <profiles>
            <profile>
              <id>java17-compatibility</id>
              <properties>
                <maven.compiler.source>17</maven.compiler.source>
                <maven.compiler.target>17</maven.compiler.target>
                <maven.compiler.release>17</maven.compiler.release>
              </properties>
            </profile>
          </profiles>
          <activeProfiles>
            <activeProfile>java17-compatibility</activeProfile>
          </activeProfiles>
        </settings>
        EOF
    
    - name: Build FlowDroid with Maven
      run: |
        cd FlowDroid
        mvn clean package -DskipTests \
          -Dmaven.compiler.source=17 \
          -Dmaven.compiler.target=17 \
          -Dmaven.compiler.release=17
      env:
        MAVEN_OPTS: "-Dmaven.compiler.source=17 -Dmaven.compiler.target=17"
    
    - name: Debug Maven Configuration
      if: failure()
      run: |
        mvn -version
        java -version
        echo "Maven Settings:"
        cat ~/.m2/settings.xml
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flowdroid-build
        path: |
          FlowDroid/target/*.jar
          FlowDroid/target/*.war
        retention-days: 5
