name: Build FlowDroid 2.14.1

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone FlowDroid Repository
      uses: actions/checkout@v3
      with:
        repository: 'secure-software-engineering/FlowDroid'
        ref: 'v2.14.1'
        fetch-depth: 1

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: |
        echo "Starting build for FlowDroid 2.14.1"
        mvn clean install -DskipTests=true

    - name: Run Tests
      run: |
        mvn test

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flowdroid-2.14.1-build
        path: |
          soot-infoflow/target/*.jar
          soot-infoflow-android/target/*.jar
          soot-infoflow-cmd/target/*.jar
          soot-infoflow-summaries/target/*.jar

    - name: Create Release Directory
      run: |
        mkdir -p release
        cp soot-infoflow/target/*-complete.jar release/
        cp soot-infoflow-android/target/*-complete.jar release/
        cp soot-infoflow-cmd/target/*-complete.jar release/
        cp soot-infoflow-summaries/target/*-complete.jar release/

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flowdroid-2.14.1-release
        path: release/
