name: Build FlowDroid 2.14.1

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Clone Soot Repository
      run: |
        git clone https://github.com/soot-oss/soot.git
        cd soot
        git checkout develop  # or specific commit/tag if needed
    
    - name: Install Soot to Local Maven Repository
      run: |
        cd soot
        mvn clean install -DskipTests
    
    - name: Clone FlowDroid Repository
      run: |
        git clone https://github.com/secure-software-engineering/FlowDroid.git
        cd FlowDroid
        git checkout v2.14.1
    
    - name: Build FlowDroid with Maven
      run: |
        cd FlowDroid
        mvn clean package -DskipTests
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flowdroid-build
        path: |
          FlowDroid/target/*.jar
          FlowDroid/target/*.war
        retention-days: 5
    
 
